FROM debian:trixie-slim

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		ca-certificates \
		gawk \
		wget \
	; \
	apt-get dist-clean

COPY .local-scripts/gather-dpkg.sh /usr/local/bin/

CMD ["gather-dpkg.sh"]
